### ISSUE TITLE
npm install -g light-swift fails

### ISSUE THREAD

**Issue by csaroff** [bancek/light-swift#2]
I was following your README and I tried

``` bash
npm install -g light-swift
```

And I'm receiving a bunch of node-gyp errors from the xattr-async dependency.

``` bash
$ npm install -g light-swift
```

``` bash
npm WARN deprecated lodash@2.3.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
WARN engine xattr-async@0.1.3: wanted: {"node":"~1.10.2"} (current: {"node":"0.12.7","npm":"2.11.3"})

> xattr-async@0.1.3 install /usr/local/lib/node_modules/light-swift/node_modules/xattr-async
> node-gyp rebuild

  CXX(target) Release/obj.target/xattrAsync/src/xattr-async.o
../src/xattr-async.cpp:69:23: error: expected ';' after expression
    String::AsciiValue ascii_value(value);
                      ^
                      ;
../src/xattr-async.cpp:69:13: error: no member named 'AsciiValue' in 'v8::String'
    String::AsciiValue ascii_value(value);
    ~~~~~~~~^
```

... more of the same ...

``` bash
v8::NonCopyablePersistentTraits<v8::Function> >'named 'Call' in 'v8::Persistent<v8::Function, \
        baton->callback->Call(Context::GetCurrent()->Global(), argc, argv);
        ~~~~~~~~~~~~~~~  ^
../src/xattr-async.cpp:187:40: error: no member named 'GetCurrent' in 'v8::Context'
        baton->callback->Call(Context::GetCurrent()->Global(), argc, argv);
                              ~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/xattrAsync/src/xattr-async.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/light-swift/node_modules/xattr-async
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN deprecated bignumber.js@2.0.0: critical bug fixed in v2.0.4

> kerberos@0.0.3 install /usr/local/lib/node_modules/light-swift/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o

> bson@0.2.5 install /usr/local/lib/node_modules/light-swift/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "light-swift"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! xattr-async@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xattr-async@0.1.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the xattr-async package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls xattr-async
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/csaroff/CloudOE/Event-Notifier-GHE/user-preferences-api/npm-debug.log
```

Sorry for the massive logs.  I didn't want to leave too much out.

I'm attempting to install on OSX

``` bash
$ sw_vers
```

``` bash
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F1509
```

**Comment by bancek** [comment]
I've added support for node >= 0.10 for node-xattr-async library and bumped the dependencies. This should work now.

**Comment by csaroff** [comment]
Indeed.  Thank you very much for update.  This is a really awesome project!
